apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apiclarity.name" . }}-headers-to-ignore-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
data:
  request.headers: |-
    x-forwarded-proto
    x-request-id
    x-b3-traceid
    x-b3-sampled
    x-b3-spanid
    x-span-name
    x-b3-parentspanid
    A-IM
    Accept
    Accept-Charset
    Accept-Encoding
    Accept-Language
    Accept-Datetime
    Access-Control-Request-Method
    Access-Control-Request-Headers
    Authorization
    Cache-Control
    Connection
    Content-Length
    Content-Type
    Cookie
    Date
    Expect
    Forwarded
    From
    Host
    If-Match
    If-Modified-Since
    If-None-Match
    If-Range
    If-Unmodified-Since
    Max-Forwards
    Origin
    Pragma
    Proxy-Authorization
    Range
    Referer
    TE
    User-Agent
    Upgrade
    Via
    Warning
  response.headers: |-
    x-application-context
    Access-Control-Allow-Credentials
    Access-Control-Allow-Headers
    Access-Control-Allow-Methods
    Access-Control-Allow-Origin
    Access-Control-Expose-Headers
    Access-Control-Max-Age
    Accept-Ranges
    Age
    Allow
    Alternate-Protocol
    Cache-Control
    Client-Date
    Client-Peer
    Client-Response-Num
    Connection
    Content-Disposition
    Content-Encoding
    Content-Language
    Content-Length
    Content-Location
    Content-MD5
    Content-Range
    Content-Security-Policy
    X-Content-Security-Policy
    X-WebKit-CSP
    Content-Security-Policy-Report-Only
    Content-Type
    Date
    ETag
    Expires
    HTTP
    Keep-Alive
    Last-Modified
    Link
    Location
    P3P
    Pragma
    Proxy-Authenticate
    Proxy-Connection
    Refresh
    Retry-After
    Server
    Set-Cookie
    Status
    Strict-Transport-Security
    Timing-Allow-Origin
    Trailer
    Transfer-Encoding
    Upgrade
    Vary
    Via
    Warning
    WWW-Authenticate
    X-Aspnet-Version
    X-Content-Type-Options
    X-Frame-Options
    X-Permitted-Cross-Domain-Policies
    X-Pingback
    X-Powered-By
    X-Robots-Tag
    X-UA-Compatible
    X-XSS-Protection
